### ISSUE TITLE
unnecessary customizations in .vscode/settings.json 

### ISSUE THREAD

**Issue by emmanuelnk** [HoukasaurusRex/the-perfect-express-ts-server#1]
There are what I believe to be unnecessary workbench customizations in .vscode/settings.json. They turn the workbench sidebar orange.

https://github.com/HoukasaurusRex/the-perfect-express-ts-server/blob/3fbf15fba86078409d60b09766c4996d11662825/.vscode/settings.json#L2-L20

**Comment by HoukasaurusRex** [comment]
Yeah I always forget to .gitignore those
